hydra:
  run:
    dir: /student/tahmad8/Videos/deep_ev_tracker/eval_results/${model.name}/${now:%Y-%m-%d_%H%M%S}

gt_path: /student/tahmad8/Videos/deep_ev_tracker/gt_tracks/
running_locally: False


weights_path: /student/tahmad8/Videos/deep_ev_tracker/pretrained_weights/weights_finetuned_ec.ckpt

track_name: shitomasi_custom
representation: time_surfaces_v2_5
patch_size: 31
visualize: True
dt_track_vis: 0.2

# Composing nested config with default
defaults:
  - model: correlation3_unscaled
# Pytorch lightning trainer's argument
trainer:
  gpus: [0]
